### ISSUE TITLE
Add TravisCI integration

### ISSUE THREAD

**Issue by jljorgenson18** [jljorgenson18/simplesmoothscroll#10]
Try to get PhantomJS working with it. It may need a polyfill for request animation frame

**Comment by ryanmcdermott** [comment]
A bit old, but will this work? https://gist.github.com/paulirish/1579671

**Comment by jljorgenson18** [comment]
Because its phantomjs it doesn't need to be perfect so I think that will work. I'll have to investigate other issues with phantomjs as well because in order for the tests to work, there needs to be set a window size.

**Comment by jljorgenson18** [comment]
Ended up using virtual firefox on travis ci
